apiVersion: v1
kind: Service
metadata:
  name: user-form-e2e-devops-backend-service
spec:
  selector:
    app: user-form-e2e-devops
  ports:
  - name: backend-port
    protocol: TCP
    port: 5000 #external port
    targetPort: 5000 #container port for backend
  type: ClusterIP
