# This file defines the Kubernetes service for the user-form-e2e-devops application. It exposes the frontend and backend components of the application. 
# But this gives error while port forwarding and is not recommended.




apiVersion: v1
kind: Service
metadata:
  name: user-form-e2e-devops-service
spec:
  selector:
    app: user-form-e2e-devops
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 #external port
    targetPort: 80 #container port for frontend
  - name: backend-port
    protocol: TCP
    port: 5000 #external port
    targetPort: 5000 #container port for backend
  type: ClusterIP
