apiVersion: v1
kind: Service
metadata:
  name: user-form-e2e-devops-frontend-service
spec:
  selector:
    app: user-form-e2e-devops
  ports:
  - name: frontend-port
    protocol: TCP
    port: 5000 #external port
    targetPort: 80 #container port for frontend
  type: ClusterIP
